logging.level.org.springframework.web: DEBUG
logging.level.uk.gov.hmcts.reform: debug

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full

logging:
  level:
    uk.gov.hmcts.reform: debug
    org.hibernate:
      SQL: debug
      type: trace
      type.descriptor.sql.BasicBinder: debug
    org.zalando.logbook: TRACE