logging.level.org.springframework.web: DEBUG
logging.level.uk.gov.hmcts.reform: debug

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full

logging:
  level:
    org.springframework:
      dao: info
      transaction: debug
      jdbc.core.JdbcTemplate: info
    org.hibernate:
      SQL: info
      type.descriptor.sql.BasicBinder: info
      engine: info
    uk.gov.hmcts.reform: debug

