ccd:
  url: ${CCD_URL:http://ccd-data-store-api}
core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

idam:
  system:
    username: ${WA_SYSTEM_USERNAME:some_user@hmcts.net}
    password: ${WA_SYSTEM_PASSWORD:password}
