
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full

logging:
  level:
    org.springframework:
      web: debug
      dao: debug
      transaction: debug
      jdbc.core.JdbcTemplate: info
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: debug
      engine: debug
    uk.gov.hmcts.reform: debug
