apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-task-management-api App
name: wa-task-management-api
home: https://github.com/hmcts/wa-task-management-api
version: 0.0.18
maintainers:
  - name: HMCTS wa team
dependencies:
  - name: java
    version: 3.4.4
    repository: '@hmctspublic'
