## NOTE:
# To run integration tests with this active profile on your local machine
# you need to start up your docker app, not minikube but the docker app.

logging:
  level:
    org.springframework:
      dao: debug
      transaction: debug
      jdbc.core.JdbcTemplate: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
      engine: debug
    uk.gov.hmcts.reform: debug
