config:
  stacktraceEnabled: false

spring:
  driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        dialect: "uk.gov.hmcts.reform.wataskmanagementapi.config.CustomPostgreSQL94Dialect"

testcontainers:
  reuse:
    enable: true
