config:
  stacktraceEnabled: false

spring:
  driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
  datasource:
    url: jdbc:tc:postgresql:11.4://localhost/cft_task_db
    properties:
    charSet: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        dialect: "uk.gov.hmcts.reform.wataskmanagementapi.config.CustomPostgreSQL94Dialect"
