-- CREATE DATABASE cft_task_db WITH OWNER=postgres ENCODING='UTF-8' CONNECTION LIMIT=-1;
CREATE ROLE wa_user SUPERUSER REPLICATION LOGIN PASSWORD 'wa_password';

GRANT CONNECT ON DATABASE cft_task_db TO wa_user;
