-- CREATE DATABASE cft_task_db WITH OWNER=postgres ENCODING='UTF-8' CONNECTION LIMIT=-1;
CREATE ROLE repl_user SUPERUSER REPLICATION LOGIN PASSWORD 'repl_password';

GRANT CONNECT ON DATABASE cft_task_db TO repl_user;
