name: Publish Swagger Specs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Swagger Publisher
        run: ./gradlew integration --tests uk.gov.hmcts.reform.wataskmanagementapi.config.OpenAPIPublisherTest
      - name: Commit to repository
        run: |
          mkdir swagger-staging
            cd swagger-staging
          git init
          git config user.email "github-platform-operations@HMCTS.NET"
          git config user.name "HMCTS Platform Operations"
          git remote add upstream https://apitoken:${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}@github.com/hmcts/cnp-api-docs.git
          git pull upstream master
          repo=`echo "$GITHUB_REPOSITORY" | cut -f2- -d/`
          echo "$(cat /tmp/swagger-specs.json)" > "docs/specs/$repo.json"
          git add "docs/specs/$repo.json"
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update spec for $repo#${GITHUB_SHA:7}"; git push --set-upstream upstream master)
